### ISSUE TITLE
error while parsing if @documentation in node_modules/codo/lib/entities/class.coffee is undefined

### ISSUE THREAD

**Issue by StevieSteven** [coffeedoc/codo#255]
I got this error message by trying parsing my code. I have got no idea why it doesn't work not anymore (I know it's a really bad error description. Sorry about that.):

node_modules/codo/lib/entities/class.coffee:144
      for (i = 0, len = ref.length; i < len; i++) {
                           ^

TypeError: Cannot read property 'length' of undefined
  at Class.module.exports.Entities.Class.Class.linkifyValue (/usr/local/lib/node_modules/codo/lib/entities/class.coffee:105:5)
  at Class.module.exports.Entities.Class.Class.linkify (/usr/local/lib/node_modules/codo/lib/entities/class.coffee:82:10)
  at Environment.module.exports.Environment.linkify (/usr/local/lib/node_modules/codo/lib/environment.coffee:130:12)
  at Object.module.exports.Codo.parseProject (/usr/local/lib/node_modules/codo/lib/codo.coffee:56:17)
  at Command.module.exports.Command.generate (/usr/local/lib/node_modules/codo/lib/command.coffee:118:24)
  at Command.module.exports.Command.run (/usr/local/lib/node_modules/codo/lib/command.coffee:87:8)
  at Function.module.exports.Command.run (/usr/local/lib/node_modules/codo/lib/command.coffee:27:13)
  at Object.<anonymous> (/usr/local/lib/node_modules/codo/bin/codo:14:19)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:442:10)
  at startup (node.js:136:18)
  at node.js:966:3

**Comment by DeveloperAlan** [comment]
Getting this error as well. @StevieSteven did you solve it by any chance?

**Comment by StevieSteven** [comment]
Hello, 
not really. I remember that there was trouble with some empty lines. But at all, I don't know how you can solve the problem  in general. 

I don't work with CoffeeScript anymore. 
JavaScript ES6 has all the features I need.

**Comment by DeveloperAlan** [comment]
Just for future reference, I had a problem with my coffeescript syntax that I had to fix. Through the process of elimination, I've just narrowed down to which one of my files had the issue. Just a silly tab character was causing the issue.
